In [2]:
#NUMPY: is a general-purpose array processing package. It provides tools to work with arrays.

In [3]:
#ARRAY: An array in python stores values of the same datatype. In python the main difference between array and list is that list stores
#values that can be of different data types whereas an array stores values of the same datatype.


In [4]:
import numpy as np

In [5]:
my_ex= [1,2,3,4]
array1= np.array(my_ex)

In [6]:
print(type(array1))

<class 'numpy.ndarray'>


In [13]:
#This is a one dimensional array
print(array1)

[1 2 3 4]


In [14]:
array1.shape

(4,)

In [15]:
my_list1= [1,2,3,4,5]
my_list2= [6,7,8,9,10]
my_list3= [11,12,13,14,15]

array2= np.array([my_list1,my_list2,my_list1])

In [16]:
#This is a multidimensional array
print(array2)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [ 1  2  3  4  5]]


In [17]:
array2.shape

(3, 5)

In [22]:
array2.reshape(5,3) 
#while reshaping make sure that the number of elements remain same 
# 3 x 5 = 5 x 3

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10,  1,  2],
       [ 3,  4,  5]])

In [23]:
# INDEXING 

In [24]:
array3= np.array([1,2,3,4,5,6,7,8])

In [26]:
array3[4]

np.int64(5)

In [29]:
array2[:,:]

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [ 1,  2,  3,  4,  5]])

In [30]:
array2[0:2, 0:2]

array([[1, 2],
       [6, 7]])

In [37]:
#INBUILT FUNCTIONS

In [43]:
array4= np.arange(0,10, step=2)

In [44]:
array4

array([0, 2, 4, 6, 8])

In [47]:
np.linspace(1,10,50)

array([ 1.        ,  1.18367347,  1.36734694,  1.55102041,  1.73469388,
        1.91836735,  2.10204082,  2.28571429,  2.46938776,  2.65306122,
        2.83673469,  3.02040816,  3.20408163,  3.3877551 ,  3.57142857,
        3.75510204,  3.93877551,  4.12244898,  4.30612245,  4.48979592,
        4.67346939,  4.85714286,  5.04081633,  5.2244898 ,  5.40816327,
        5.59183673,  5.7755102 ,  5.95918367,  6.14285714,  6.32653061,
        6.51020408,  6.69387755,  6.87755102,  7.06122449,  7.24489796,
        7.42857143,  7.6122449 ,  7.79591837,  7.97959184,  8.16326531,
        8.34693878,  8.53061224,  8.71428571,  8.89795918,  9.08163265,
        9.26530612,  9.44897959,  9.63265306,  9.81632653, 10.        ])

In [48]:
#COPY FUNCTION

#An array is a reference type because the variable stores the memory address of 
#the array, not the actual elements. When one array variable is assigned to 
#another, only the reference is copied, so both variables point to the same memory. Therefore, changes made through one variable affect the other.

In [49]:
arr= np.array([1,2,3,4,5,6,7,8])

In [52]:
arr[4:]=100
arr

array([  1,   2,   3,   4, 100, 100, 100, 100])

In [53]:
arr1= arr

In [56]:
arr1[4:]=500

In [57]:
arr1

array([  1,   2,   3,   4, 500, 500, 500, 500])

In [58]:
arr

array([  1,   2,   3,   4, 500, 500, 500, 500])

In [61]:
#Using copy function
arr1=arr.copy()

In [62]:
print(arr)
arr1[4:]=1000
print(arr1)

[  1   2   3   4 500 500 500 500]
[   1    2    3    4 1000 1000 1000 1000]


In [63]:
arr

array([  1,   2,   3,   4, 500, 500, 500, 500])